name: Change latest SHA

on:
    workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.TOLKIEN }}

jobs:
    change-sha:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4
            - name: "Get the HEAD SHA"
              run: |
                echo "CUR_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
            - name: "Do stuff"
              if: ${{ env.CUR_HEAD != vars.PREV_HEAD }}
              run: | 
                echo "Doin' stuff"
                git branch "SUPER_SAMPLE"
                git push -u origin "SUPER_SAMPLE"
                gh variable set PREV_HEAD --body $CUR_HEAD
