name: Change latest SHA

on:
    workflow_dispatch

jobs:
    change-sha:
        runs-on: ubuntu-latest
        steps:
            - name: "Print Env"
              run: | 
                echo ${{ vars.MINION }}
            - name: "Change Env"
              run: |
                gh variable set MINION --body BENIS
            - name: "Print Env, again"
              run: |
                echo ${{ vars.MINION }}
        

