name: Change latest SHA

on:
    workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.TOLKIEN }}
  NEXT_MINOR: ${{ vars.NEXT_MINOR }}
  RELEASE_BRANCH: "release/${{vars.MAYOR}}.${{vars.NEXT_MINOR}}.0"

jobs:
    change-sha:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4
            - name: "Get the HEAD SHA"
              run: |
                echo "CUR_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
            - name: "Do stuff"
              run: | 
                git branch $RELEASE_BRANCH
                git push -u origin $RELEASE_BRANCH
                gh variable set PREV_HEAD --body $CUR_HEAD
                gh variable set NEXT_MINOR --body $((NEXT_MINOR + 1))
