name: Change latest SHA

on:
    workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.TOLKIEN }}

jobs:
    change-sha:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4
            - name: "Get the HEAD SHA"
              run: |
                echo "CUR_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
            - name: "Do stuff"
              run: | 
                git branch "release/${{var.MAYOR}}.${{var.NEXT_MINOR}}.0"
                git push -u origin "SUPER_SAMPLE"
                gh variable set PREV_HEAD --body $CUR_HEAD
                gh variable set NEXT_MINOR --body $((NEXT_MINOR + 1))
