name: Change latest SHA

on:
    workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }}

jobs:
    change-sha:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4
              with:
                sparse-checkout: .
            - name: "Print Env"
              run: | 
                echo ${{ vars.MINION }}
            - name: "Change Env"
              run: |
                gh variable set MINION --body BENIS
            - name: "Print Env, again"
              run: |
                echo ${{ vars.MINION }}
        

