name: Playing with Variables

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.TOLKIEN }}
  MY_NUMBER: ${{ vars.MY_NUMBER }}

jobs:
  read-variable:
    runs-on: ubuntu-latest
    steps:
      - name: "Read it & change it!"
        run: |
          echo "The Variable stored in env is $MY_NUMBER"
          echo "The Variable stored on the repository is ${{ vars.MY_NUMBER }}"
          NEW_NUMBER=$(( MY_NUMBER + 1 ))
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Jaime-Galvez/ActionsSandbox/actions/variables/MY_NUMBER -d '{"name":"MY_NUMBER","value":"${NEW_NUMBER}"}'

  read-it-again:
    needs: read-variable
    runs-on: ubuntu-latest
    steps:
      - name: "Read it, again!"
        run: |
          echo "The Variable stored in env is $MY_NUMBER"
          echo "The Variable stored on the repository is ${{ vars.MY_NUMBER }}"

