name: Playing with Variables

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.TOLKIEN }}
  MY_NUMBER: ${{ vars.MY_NUMBER }}

jobs:
  read-variable:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "okok, I'll checkout... bastards"
        uses: actions/checkout@v4
      - name: "Read it & change it!"
        run: |
          echo "The Variable stored in env is $MY_NUMBER"
          echo "The Variable stored on the repository is ${{ vars.MY_NUMBER }}"
          NEW_NUMBER=$(( MY_NUMBER + 1 ))
          gh variable set MY_NUMBER --body ${NEW_NUMBER}

  read-it-again:
    needs: read-variable
    runs-on: ubuntu-latest
    steps:
      - name: "Read it, again!"
        run: |
          echo "The Variable stored in env is $MY_NUMBER"
          echo "The Variable stored on the repository is ${{ vars.MY_NUMBER }}"

